--- 
title: "Country Environment Factors correlated with Happiness"
author: "Ritesh Malaiya"
date: "`r Sys.Date()`"
output: word_document
description: This data is all acquired through Google Earth Engine 
documentclass: book
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
---

# Introduction {#intro}


## Context
Assessing country-level social and economic statistics are often limited to socio-economic data. Not any more! This dataset will be maintained and updated with miscellaneous environmental data for countries across the globe.

## Content
This data is all acquired through Google Earth Engine (https://earthengine.google.com/) where publicly available remote sensing datasets have been uploaded to the cloud to be manipulated by the average Joe like you and I. Most of the data is derived by calculating the mean for each country at a reduction scale of about 10km.

## Inspiration
Can you use environmental statistics to predict social and economic data?
Are people more happy in sunny countries?
How do economies in forested countries compare with those dominated by grassland/desert?


## Research Question (scope of this book)

How do the 137 countries differ on these variables?


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
